@startuml classes
set namespaceSeparator none
class "CurrentConditionsDisplay" as level1_single_observer_modular.CurrentConditionsDisplay {
  _humidity : float
  _pressure : float
  _temperature : float
  __init__(weather_station)
  display()
  update(temperature, humidity, pressure)
}
class "WeatherStation" as level1_single_observer_modular.WeatherStation {
  _humidity : float
  _observers : list
  _pressure : float
  _temperature : float
  __init__()
  notify_observers()
  register_observer(observer)
  remove_observer(observer)
  set_measurements(temperature, humidity, pressure)
}
@enduml
